# Default configuration values
shared_volume_path: /Users/ashjay/Desktop/Projects/xployt/xployt-main-server/local_storage/repos/
repo_id: vuln_node_express
output_root: output
llm_model: gpt-4o
temperature: 0.1
metadata_max_files: 30
select_vul_files_limit: 30
file_limit_per_subset_when_selecting_pipelines: 8