# Default configuration values
shared_volume_path: E:/PROJECTS/ACADAMIC/Xployt-ai/REPOS/
repo_id: vuln_node_express
codebase_path: E:/PROJECTS/ACADAMIC/Xployt-ai/REPOS/vuln_node_express
output_root: output
llm_model: gpt-4o
temperature: 0.1
metadata_max_files: 30
select_vul_files_limit: 60
file_limit_per_subset_when_selecting_pipelines: 20